FROM node:10.9.0-alpine
LABEL maintainer="Elena Shchekina"
WORKDIR /Users/edit1/Documents/myJava/thumbtack_online_school_2019_2_elena_shchekina//Users/edit1/Documents/docker_practice/tt-docker-practise
COPY . ./
RUN npm install
EXPOSE 8080
CMD ["npm","start"]